version: '3.4'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: yourStrong(!)Password
    ports:
     - 1433:1433
  messagebroker:
    image: rabbitmq:3-management
    ports:
     - 8080:15672
     - 5672:5672
  cache:
    image: redis:7.2.4-alpine
    ports:
      - 6379:6379
    command: redis-server --save 1 1 --loglevel warning --appendonly yes
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local